// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: proto/resiliency/resiliency.proto

package resiliency

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ResiliencyService_UnaryResiliency_FullMethodName           = "/resiliency.ResiliencyService/UnaryResiliency"
	ResiliencyService_StreamingResiliency_FullMethodName       = "/resiliency.ResiliencyService/StreamingResiliency"
	ResiliencyService_ClientStreamingResiliency_FullMethodName = "/resiliency.ResiliencyService/ClientStreamingResiliency"
	ResiliencyService_BiDirectionalResiliency_FullMethodName   = "/resiliency.ResiliencyService/BiDirectionalResiliency"
)

// ResiliencyServiceClient is the client API for ResiliencyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResiliencyServiceClient interface {
	UnaryResiliency(ctx context.Context, in *ResiliencyRequest, opts ...grpc.CallOption) (*ResiliencyResponse, error)
	StreamingResiliency(ctx context.Context, in *ResiliencyRequest, opts ...grpc.CallOption) (ResiliencyService_StreamingResiliencyClient, error)
	ClientStreamingResiliency(ctx context.Context, opts ...grpc.CallOption) (ResiliencyService_ClientStreamingResiliencyClient, error)
	BiDirectionalResiliency(ctx context.Context, opts ...grpc.CallOption) (ResiliencyService_BiDirectionalResiliencyClient, error)
}

type resiliencyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewResiliencyServiceClient(cc grpc.ClientConnInterface) ResiliencyServiceClient {
	return &resiliencyServiceClient{cc}
}

func (c *resiliencyServiceClient) UnaryResiliency(ctx context.Context, in *ResiliencyRequest, opts ...grpc.CallOption) (*ResiliencyResponse, error) {
	out := new(ResiliencyResponse)
	err := c.cc.Invoke(ctx, ResiliencyService_UnaryResiliency_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resiliencyServiceClient) StreamingResiliency(ctx context.Context, in *ResiliencyRequest, opts ...grpc.CallOption) (ResiliencyService_StreamingResiliencyClient, error) {
	stream, err := c.cc.NewStream(ctx, &ResiliencyService_ServiceDesc.Streams[0], ResiliencyService_StreamingResiliency_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &resiliencyServiceStreamingResiliencyClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ResiliencyService_StreamingResiliencyClient interface {
	Recv() (*ResiliencyResponse, error)
	grpc.ClientStream
}

type resiliencyServiceStreamingResiliencyClient struct {
	grpc.ClientStream
}

func (x *resiliencyServiceStreamingResiliencyClient) Recv() (*ResiliencyResponse, error) {
	m := new(ResiliencyResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *resiliencyServiceClient) ClientStreamingResiliency(ctx context.Context, opts ...grpc.CallOption) (ResiliencyService_ClientStreamingResiliencyClient, error) {
	stream, err := c.cc.NewStream(ctx, &ResiliencyService_ServiceDesc.Streams[1], ResiliencyService_ClientStreamingResiliency_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &resiliencyServiceClientStreamingResiliencyClient{stream}
	return x, nil
}

type ResiliencyService_ClientStreamingResiliencyClient interface {
	Send(*ResiliencyRequest) error
	CloseAndRecv() (*ResiliencyResponse, error)
	grpc.ClientStream
}

type resiliencyServiceClientStreamingResiliencyClient struct {
	grpc.ClientStream
}

func (x *resiliencyServiceClientStreamingResiliencyClient) Send(m *ResiliencyRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *resiliencyServiceClientStreamingResiliencyClient) CloseAndRecv() (*ResiliencyResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ResiliencyResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *resiliencyServiceClient) BiDirectionalResiliency(ctx context.Context, opts ...grpc.CallOption) (ResiliencyService_BiDirectionalResiliencyClient, error) {
	stream, err := c.cc.NewStream(ctx, &ResiliencyService_ServiceDesc.Streams[2], ResiliencyService_BiDirectionalResiliency_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &resiliencyServiceBiDirectionalResiliencyClient{stream}
	return x, nil
}

type ResiliencyService_BiDirectionalResiliencyClient interface {
	Send(*ResiliencyRequest) error
	Recv() (*ResiliencyResponse, error)
	grpc.ClientStream
}

type resiliencyServiceBiDirectionalResiliencyClient struct {
	grpc.ClientStream
}

func (x *resiliencyServiceBiDirectionalResiliencyClient) Send(m *ResiliencyRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *resiliencyServiceBiDirectionalResiliencyClient) Recv() (*ResiliencyResponse, error) {
	m := new(ResiliencyResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ResiliencyServiceServer is the server API for ResiliencyService service.
// All implementations must embed UnimplementedResiliencyServiceServer
// for forward compatibility
type ResiliencyServiceServer interface {
	UnaryResiliency(context.Context, *ResiliencyRequest) (*ResiliencyResponse, error)
	StreamingResiliency(*ResiliencyRequest, ResiliencyService_StreamingResiliencyServer) error
	ClientStreamingResiliency(ResiliencyService_ClientStreamingResiliencyServer) error
	BiDirectionalResiliency(ResiliencyService_BiDirectionalResiliencyServer) error
	mustEmbedUnimplementedResiliencyServiceServer()
}

// UnimplementedResiliencyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedResiliencyServiceServer struct {
}

func (UnimplementedResiliencyServiceServer) UnaryResiliency(context.Context, *ResiliencyRequest) (*ResiliencyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnaryResiliency not implemented")
}
func (UnimplementedResiliencyServiceServer) StreamingResiliency(*ResiliencyRequest, ResiliencyService_StreamingResiliencyServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamingResiliency not implemented")
}
func (UnimplementedResiliencyServiceServer) ClientStreamingResiliency(ResiliencyService_ClientStreamingResiliencyServer) error {
	return status.Errorf(codes.Unimplemented, "method ClientStreamingResiliency not implemented")
}
func (UnimplementedResiliencyServiceServer) BiDirectionalResiliency(ResiliencyService_BiDirectionalResiliencyServer) error {
	return status.Errorf(codes.Unimplemented, "method BiDirectionalResiliency not implemented")
}
func (UnimplementedResiliencyServiceServer) mustEmbedUnimplementedResiliencyServiceServer() {}

// UnsafeResiliencyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResiliencyServiceServer will
// result in compilation errors.
type UnsafeResiliencyServiceServer interface {
	mustEmbedUnimplementedResiliencyServiceServer()
}

func RegisterResiliencyServiceServer(s grpc.ServiceRegistrar, srv ResiliencyServiceServer) {
	s.RegisterService(&ResiliencyService_ServiceDesc, srv)
}

func _ResiliencyService_UnaryResiliency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResiliencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResiliencyServiceServer).UnaryResiliency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResiliencyService_UnaryResiliency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResiliencyServiceServer).UnaryResiliency(ctx, req.(*ResiliencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResiliencyService_StreamingResiliency_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ResiliencyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ResiliencyServiceServer).StreamingResiliency(m, &resiliencyServiceStreamingResiliencyServer{stream})
}

type ResiliencyService_StreamingResiliencyServer interface {
	Send(*ResiliencyResponse) error
	grpc.ServerStream
}

type resiliencyServiceStreamingResiliencyServer struct {
	grpc.ServerStream
}

func (x *resiliencyServiceStreamingResiliencyServer) Send(m *ResiliencyResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ResiliencyService_ClientStreamingResiliency_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ResiliencyServiceServer).ClientStreamingResiliency(&resiliencyServiceClientStreamingResiliencyServer{stream})
}

type ResiliencyService_ClientStreamingResiliencyServer interface {
	SendAndClose(*ResiliencyResponse) error
	Recv() (*ResiliencyRequest, error)
	grpc.ServerStream
}

type resiliencyServiceClientStreamingResiliencyServer struct {
	grpc.ServerStream
}

func (x *resiliencyServiceClientStreamingResiliencyServer) SendAndClose(m *ResiliencyResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *resiliencyServiceClientStreamingResiliencyServer) Recv() (*ResiliencyRequest, error) {
	m := new(ResiliencyRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ResiliencyService_BiDirectionalResiliency_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ResiliencyServiceServer).BiDirectionalResiliency(&resiliencyServiceBiDirectionalResiliencyServer{stream})
}

type ResiliencyService_BiDirectionalResiliencyServer interface {
	Send(*ResiliencyResponse) error
	Recv() (*ResiliencyRequest, error)
	grpc.ServerStream
}

type resiliencyServiceBiDirectionalResiliencyServer struct {
	grpc.ServerStream
}

func (x *resiliencyServiceBiDirectionalResiliencyServer) Send(m *ResiliencyResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *resiliencyServiceBiDirectionalResiliencyServer) Recv() (*ResiliencyRequest, error) {
	m := new(ResiliencyRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ResiliencyService_ServiceDesc is the grpc.ServiceDesc for ResiliencyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResiliencyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "resiliency.ResiliencyService",
	HandlerType: (*ResiliencyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UnaryResiliency",
			Handler:    _ResiliencyService_UnaryResiliency_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamingResiliency",
			Handler:       _ResiliencyService_StreamingResiliency_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ClientStreamingResiliency",
			Handler:       _ResiliencyService_ClientStreamingResiliency_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "BiDirectionalResiliency",
			Handler:       _ResiliencyService_BiDirectionalResiliency_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/resiliency/resiliency.proto",
}

const (
	ResiliencyWithMetadataService_UnaryResiliencyWithMetadata_FullMethodName           = "/resiliency.ResiliencyWithMetadataService/UnaryResiliencyWithMetadata"
	ResiliencyWithMetadataService_StreamingResiliencyWithMetadata_FullMethodName       = "/resiliency.ResiliencyWithMetadataService/StreamingResiliencyWithMetadata"
	ResiliencyWithMetadataService_ClientStreamingResiliencyWithMetadata_FullMethodName = "/resiliency.ResiliencyWithMetadataService/ClientStreamingResiliencyWithMetadata"
	ResiliencyWithMetadataService_BiDirectionalResiliencyWithMetadata_FullMethodName   = "/resiliency.ResiliencyWithMetadataService/BiDirectionalResiliencyWithMetadata"
)

// ResiliencyWithMetadataServiceClient is the client API for ResiliencyWithMetadataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResiliencyWithMetadataServiceClient interface {
	UnaryResiliencyWithMetadata(ctx context.Context, in *ResiliencyRequest, opts ...grpc.CallOption) (*ResiliencyResponse, error)
	StreamingResiliencyWithMetadata(ctx context.Context, in *ResiliencyRequest, opts ...grpc.CallOption) (ResiliencyWithMetadataService_StreamingResiliencyWithMetadataClient, error)
	ClientStreamingResiliencyWithMetadata(ctx context.Context, opts ...grpc.CallOption) (ResiliencyWithMetadataService_ClientStreamingResiliencyWithMetadataClient, error)
	BiDirectionalResiliencyWithMetadata(ctx context.Context, opts ...grpc.CallOption) (ResiliencyWithMetadataService_BiDirectionalResiliencyWithMetadataClient, error)
}

type resiliencyWithMetadataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewResiliencyWithMetadataServiceClient(cc grpc.ClientConnInterface) ResiliencyWithMetadataServiceClient {
	return &resiliencyWithMetadataServiceClient{cc}
}

func (c *resiliencyWithMetadataServiceClient) UnaryResiliencyWithMetadata(ctx context.Context, in *ResiliencyRequest, opts ...grpc.CallOption) (*ResiliencyResponse, error) {
	out := new(ResiliencyResponse)
	err := c.cc.Invoke(ctx, ResiliencyWithMetadataService_UnaryResiliencyWithMetadata_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resiliencyWithMetadataServiceClient) StreamingResiliencyWithMetadata(ctx context.Context, in *ResiliencyRequest, opts ...grpc.CallOption) (ResiliencyWithMetadataService_StreamingResiliencyWithMetadataClient, error) {
	stream, err := c.cc.NewStream(ctx, &ResiliencyWithMetadataService_ServiceDesc.Streams[0], ResiliencyWithMetadataService_StreamingResiliencyWithMetadata_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &resiliencyWithMetadataServiceStreamingResiliencyWithMetadataClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ResiliencyWithMetadataService_StreamingResiliencyWithMetadataClient interface {
	Recv() (*ResiliencyResponse, error)
	grpc.ClientStream
}

type resiliencyWithMetadataServiceStreamingResiliencyWithMetadataClient struct {
	grpc.ClientStream
}

func (x *resiliencyWithMetadataServiceStreamingResiliencyWithMetadataClient) Recv() (*ResiliencyResponse, error) {
	m := new(ResiliencyResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *resiliencyWithMetadataServiceClient) ClientStreamingResiliencyWithMetadata(ctx context.Context, opts ...grpc.CallOption) (ResiliencyWithMetadataService_ClientStreamingResiliencyWithMetadataClient, error) {
	stream, err := c.cc.NewStream(ctx, &ResiliencyWithMetadataService_ServiceDesc.Streams[1], ResiliencyWithMetadataService_ClientStreamingResiliencyWithMetadata_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &resiliencyWithMetadataServiceClientStreamingResiliencyWithMetadataClient{stream}
	return x, nil
}

type ResiliencyWithMetadataService_ClientStreamingResiliencyWithMetadataClient interface {
	Send(*ResiliencyRequest) error
	CloseAndRecv() (*ResiliencyResponse, error)
	grpc.ClientStream
}

type resiliencyWithMetadataServiceClientStreamingResiliencyWithMetadataClient struct {
	grpc.ClientStream
}

func (x *resiliencyWithMetadataServiceClientStreamingResiliencyWithMetadataClient) Send(m *ResiliencyRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *resiliencyWithMetadataServiceClientStreamingResiliencyWithMetadataClient) CloseAndRecv() (*ResiliencyResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ResiliencyResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *resiliencyWithMetadataServiceClient) BiDirectionalResiliencyWithMetadata(ctx context.Context, opts ...grpc.CallOption) (ResiliencyWithMetadataService_BiDirectionalResiliencyWithMetadataClient, error) {
	stream, err := c.cc.NewStream(ctx, &ResiliencyWithMetadataService_ServiceDesc.Streams[2], ResiliencyWithMetadataService_BiDirectionalResiliencyWithMetadata_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &resiliencyWithMetadataServiceBiDirectionalResiliencyWithMetadataClient{stream}
	return x, nil
}

type ResiliencyWithMetadataService_BiDirectionalResiliencyWithMetadataClient interface {
	Send(*ResiliencyRequest) error
	Recv() (*ResiliencyResponse, error)
	grpc.ClientStream
}

type resiliencyWithMetadataServiceBiDirectionalResiliencyWithMetadataClient struct {
	grpc.ClientStream
}

func (x *resiliencyWithMetadataServiceBiDirectionalResiliencyWithMetadataClient) Send(m *ResiliencyRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *resiliencyWithMetadataServiceBiDirectionalResiliencyWithMetadataClient) Recv() (*ResiliencyResponse, error) {
	m := new(ResiliencyResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ResiliencyWithMetadataServiceServer is the server API for ResiliencyWithMetadataService service.
// All implementations must embed UnimplementedResiliencyWithMetadataServiceServer
// for forward compatibility
type ResiliencyWithMetadataServiceServer interface {
	UnaryResiliencyWithMetadata(context.Context, *ResiliencyRequest) (*ResiliencyResponse, error)
	StreamingResiliencyWithMetadata(*ResiliencyRequest, ResiliencyWithMetadataService_StreamingResiliencyWithMetadataServer) error
	ClientStreamingResiliencyWithMetadata(ResiliencyWithMetadataService_ClientStreamingResiliencyWithMetadataServer) error
	BiDirectionalResiliencyWithMetadata(ResiliencyWithMetadataService_BiDirectionalResiliencyWithMetadataServer) error
	mustEmbedUnimplementedResiliencyWithMetadataServiceServer()
}

// UnimplementedResiliencyWithMetadataServiceServer must be embedded to have forward compatible implementations.
type UnimplementedResiliencyWithMetadataServiceServer struct {
}

func (UnimplementedResiliencyWithMetadataServiceServer) UnaryResiliencyWithMetadata(context.Context, *ResiliencyRequest) (*ResiliencyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnaryResiliencyWithMetadata not implemented")
}
func (UnimplementedResiliencyWithMetadataServiceServer) StreamingResiliencyWithMetadata(*ResiliencyRequest, ResiliencyWithMetadataService_StreamingResiliencyWithMetadataServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamingResiliencyWithMetadata not implemented")
}
func (UnimplementedResiliencyWithMetadataServiceServer) ClientStreamingResiliencyWithMetadata(ResiliencyWithMetadataService_ClientStreamingResiliencyWithMetadataServer) error {
	return status.Errorf(codes.Unimplemented, "method ClientStreamingResiliencyWithMetadata not implemented")
}
func (UnimplementedResiliencyWithMetadataServiceServer) BiDirectionalResiliencyWithMetadata(ResiliencyWithMetadataService_BiDirectionalResiliencyWithMetadataServer) error {
	return status.Errorf(codes.Unimplemented, "method BiDirectionalResiliencyWithMetadata not implemented")
}
func (UnimplementedResiliencyWithMetadataServiceServer) mustEmbedUnimplementedResiliencyWithMetadataServiceServer() {
}

// UnsafeResiliencyWithMetadataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResiliencyWithMetadataServiceServer will
// result in compilation errors.
type UnsafeResiliencyWithMetadataServiceServer interface {
	mustEmbedUnimplementedResiliencyWithMetadataServiceServer()
}

func RegisterResiliencyWithMetadataServiceServer(s grpc.ServiceRegistrar, srv ResiliencyWithMetadataServiceServer) {
	s.RegisterService(&ResiliencyWithMetadataService_ServiceDesc, srv)
}

func _ResiliencyWithMetadataService_UnaryResiliencyWithMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResiliencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResiliencyWithMetadataServiceServer).UnaryResiliencyWithMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResiliencyWithMetadataService_UnaryResiliencyWithMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResiliencyWithMetadataServiceServer).UnaryResiliencyWithMetadata(ctx, req.(*ResiliencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResiliencyWithMetadataService_StreamingResiliencyWithMetadata_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ResiliencyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ResiliencyWithMetadataServiceServer).StreamingResiliencyWithMetadata(m, &resiliencyWithMetadataServiceStreamingResiliencyWithMetadataServer{stream})
}

type ResiliencyWithMetadataService_StreamingResiliencyWithMetadataServer interface {
	Send(*ResiliencyResponse) error
	grpc.ServerStream
}

type resiliencyWithMetadataServiceStreamingResiliencyWithMetadataServer struct {
	grpc.ServerStream
}

func (x *resiliencyWithMetadataServiceStreamingResiliencyWithMetadataServer) Send(m *ResiliencyResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ResiliencyWithMetadataService_ClientStreamingResiliencyWithMetadata_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ResiliencyWithMetadataServiceServer).ClientStreamingResiliencyWithMetadata(&resiliencyWithMetadataServiceClientStreamingResiliencyWithMetadataServer{stream})
}

type ResiliencyWithMetadataService_ClientStreamingResiliencyWithMetadataServer interface {
	SendAndClose(*ResiliencyResponse) error
	Recv() (*ResiliencyRequest, error)
	grpc.ServerStream
}

type resiliencyWithMetadataServiceClientStreamingResiliencyWithMetadataServer struct {
	grpc.ServerStream
}

func (x *resiliencyWithMetadataServiceClientStreamingResiliencyWithMetadataServer) SendAndClose(m *ResiliencyResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *resiliencyWithMetadataServiceClientStreamingResiliencyWithMetadataServer) Recv() (*ResiliencyRequest, error) {
	m := new(ResiliencyRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ResiliencyWithMetadataService_BiDirectionalResiliencyWithMetadata_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ResiliencyWithMetadataServiceServer).BiDirectionalResiliencyWithMetadata(&resiliencyWithMetadataServiceBiDirectionalResiliencyWithMetadataServer{stream})
}

type ResiliencyWithMetadataService_BiDirectionalResiliencyWithMetadataServer interface {
	Send(*ResiliencyResponse) error
	Recv() (*ResiliencyRequest, error)
	grpc.ServerStream
}

type resiliencyWithMetadataServiceBiDirectionalResiliencyWithMetadataServer struct {
	grpc.ServerStream
}

func (x *resiliencyWithMetadataServiceBiDirectionalResiliencyWithMetadataServer) Send(m *ResiliencyResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *resiliencyWithMetadataServiceBiDirectionalResiliencyWithMetadataServer) Recv() (*ResiliencyRequest, error) {
	m := new(ResiliencyRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ResiliencyWithMetadataService_ServiceDesc is the grpc.ServiceDesc for ResiliencyWithMetadataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResiliencyWithMetadataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "resiliency.ResiliencyWithMetadataService",
	HandlerType: (*ResiliencyWithMetadataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UnaryResiliencyWithMetadata",
			Handler:    _ResiliencyWithMetadataService_UnaryResiliencyWithMetadata_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamingResiliencyWithMetadata",
			Handler:       _ResiliencyWithMetadataService_StreamingResiliencyWithMetadata_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ClientStreamingResiliencyWithMetadata",
			Handler:       _ResiliencyWithMetadataService_ClientStreamingResiliencyWithMetadata_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "BiDirectionalResiliencyWithMetadata",
			Handler:       _ResiliencyWithMetadataService_BiDirectionalResiliencyWithMetadata_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/resiliency/resiliency.proto",
}
